### ISSUE TITLE
Use Btrfs for persistence partition

### ISSUE THREAD

**Issue by THS-on** [imedias/lernstickAdvanced#22]
Currently we use an ext for the persistence partition. 
This works fine for most cases, but Btrfs makes snapshots and backups easier.

## Findings
* Manually creating a partition works with an unmodified live-boot.
* Btrfs cannot create an snapshot of a subvolume/partition if there is an active swapfile on it. 
  This meas that we cannot snapshot the whole persistence partition because of swapspace.
* Having the `rw` directory as an subvolume works and snapshots can be successfully created.
* Btrfs has a feature called `seed device`
* Restoring or booting into a snapshot works by changing the default subvolume to the snapshot.
  This is unfortunate because of swapspace (and maybe overlayfs) we cannot change our root subvolume.
* Booting a snapshot for non root subvolumes has to be implemented in live-boot.
* To exclude files from a snapshot they must be in a different subvolume. This means that all directories that should not be snapshot (like temp or cache directories) must be created as subvolumes.
* A possible layout is documented here https://en.opensuse.org/SDB:BTRFS or https://wiki.archlinux.org/index.php/Snapper#Suggested_filesystem_layout
* If we don't use a nested layout and use a structure with @ we need to modify live-boot to mount the subvolumes correctly.
* Snapper stores the path where the subvolume is mounted. The persistence partition is mounted at  `/run/live/persistence/sdX` but this is not stable. In our case the we could create a stable mount to the persistence partition or change the config with lernstick-config.
* Snapper config could be on it's own subvolume to exclude it from normal `/etc` snapshots.

## TODO
- [ ] create a subvolume layout
- [ ] Include btrfs-progs by default
- [ ] Add support for btrfs in dlcopy
- [ ] Integrate Snapper or other snapshot manager
- [ ] Add a way to restore backups in a user friendly way

Next step is testing subvolumes layout and creating the partition automatically.
